services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend_ui
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    container_name: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  es_data:
    driver: local

networks:
  app_network:
    name: app_network
    driver: bridge
